AlertProcedureApp/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainpage/',include("mainpage.urls")),
    path('newyear/',include("newyear.urls")),
    path('tasks/',include("tasks.urls")),
]

mainpage/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path("",views.index, name="index"),
    path("route1",views.route1,name="route1"),
    path("reserved",views.reserved, name="reserve"),
    path("<str:person>",views.greet,name="greet"),
    
]

newyear/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.index, name="index")
]

tasks/urls.py
from django.urls import path
from . import views
app_name='tasks'
urlpatterns=[
    path("",views.index, name="index"),
    path("add/",views.add, name="add"),
]

mainpage/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

mainpage/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"mainpage/index.html")

def route1(request):
    return HttpResponse("A different Landing Page!")

def greet(request,person):
    return render(request,"mainpage/greet.html",{"name":person.capitalize()})

def reserved(req):
    return HttpResponse("This Page is reserved!")

newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now=datetime.datetime.now()
    return render(request,"newyear/index.html",{"NY":now.month and now.day})

tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

class NewTask(forms.Form):
    task=forms.CharField(label="New Task")

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"]=[]
    return render(request,"tasks/index.html",{"tasks":request.session["tasks"]})

def add(request):
    if request.method=="POST":
        form=NewTask(request.POST)
        if form.is_valid():
            task=form.cleaned_data["task"]
            request.session["tasks"]+=[task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request,"tasks/add.html",{"form":form})

    return render(request,"tasks/add.html",{"form":NewTask()})

mainpage/templates/mainpage/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Greeting!</title>
</head>
<body>
    <h1>Hello, {{name}}</h1>
</body>
</html>

mainpage/templates/mainpage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main Page</title>
    <link rel="stylesheet" href="{% static 'mainpage/styles.css' %}">
</head>
<body>
    <h1>The Main page...</h1>
</body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Is it New Year's?</title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>
<body>
    {% if newyear %}
    <h1>YES</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %}

</body>
</html>

tasks/templates/tasks/add.html
{%extends "tasks/layout.html" %}
{% block body%}
<h1>Add Task</h1>
<form action="{%url 'tasks:add'%}" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
<a href="{% url 'tasks:index' %}">View Tasks</a>

{%endblock%}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body%}
<h1>Tasks</h1>
<ul>
    {% for i in tasks %}
    <li>{{ i }}</li>
    {%endfor%}
</ul>
<a href="{%url 'tasks:add'%}">Add a New Task</a>

{%endblock%}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks</title>
</head>
<body>
    {% block body%}

    {% endblock %}
    
</body>
</html>